apiVersion: v1
kind: Pod
metadata:
  name: health-exec
spec:
  containers:
    - name: nginx
      image: master:5000/nginx:1.13
      ports:
        - containerPort: 80
      #会替换容器默认的命令
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5