apiVersion: v1
kind: Pod
metadata:
  name: health-httpget
spec:
  containers:
    - name: nginx
      image: master:5000/nginx:1.13
      ports:
        - containerPort: 80
      #会替换容器默认的命令
      args:
        - /bin/sh
        - -c
        - sleep 10; rm -rf /usr/share/nginx/html/index.html; sleep 600
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3