apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.31.161
        hostname: master
      - ip: 192.168.31.223
        hostname: node1
      - ip: 192.168.31.212
        hostname: node2
    ports:
      - port: 49152
        protocol: TCP