apiVersion: v1
kind: Pod
metadata:
  name: doublec
  labels:
    app: web
    env: test
spec:
  containers:
    - name: nginx
      image: master:5000/nginx:1.13
      ports:
        - containerPort: 80
          #映射到节点port
          hostPort: 80
      volumeMounts:
        - name: gluster-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: gluster-volume
      persistentVolumeClaim:
        claimName: gluster