apiVersion: v1
kind: Service
metadata:
  # endpoints和 service靠名字关联
  name: glusterfs
  namespace: default
spec:
  ports:
    - port: 49152
      protocol: TCP
      targetPort: 49152
  sessionAffinity: None
  type: ClusterIP