# 参考 pod-inter-act
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: lalala
spec:
  containers:
    - name: mysql
      image: master:5000/mysql:5.7
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
# 配置volume挂载
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mysql