apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    type: disk #可以写 SSD disk之类的
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/mysql"
    server: master
    readOnly: false